language: node_js
node_js:
- node
install:
- npm install
- npm install marpat
before_script:
- node --version
- npm --version
env:
  global:
  - NODE_ENV=test
  - secure: Awd5Vv74r+FULeyKC/eLINFbDuOgHLJsxn/sS8Dw1BYkwe2zcTXIGCm3ppXT8TMZKOaGXmXLp2f+trYX3KbnlRbgZqvUxzw5cReX4dsPUUYiY40Eal4qhHJDxPti7WAOEhQJYrDcwYiXMEBGaHrhawJPj+FjA1Xja35cEFEawkhKIYK8hN2VTMTxHkw3g6SyqbjP97Zgdmgvf7idYsVkXLzCG2DDO8svXX8/Gcn17J92BPdVJUEoCUCXl11JSqqAnq8nablHRsqIegoM55kCTV06k9CdeR/wdc8v0D6QVLaWjYk9Tq4KpznDNsKoCIbtz4hvm+RBPBgZ/P5Q7Jz0lqnmzVonsyBieY1GfR2JAduREe7gxFLhPRsthIGP8fLKh707PHqJqPKMiy7QPFCNqRqfhgPeMH+vAY07Lsgq4ksMVunPTWCVgHgSTfGvZTkwNIQ6RqUd0sL2EdhoiVtadnoiIEWYr8mOSI7fpVH5W3VC11c7m6hcWX9TXarL/yIFmlaJWMWEOP83xFpe9FWVSI3U4jSwqzQllqXvfVRgYOrWc8xZfabtlO02a+2eX3cstnc1v62nKGYJOo8jQ+JxUt3wK/ZsapYGPBCMd0mRGI867ce77Fqg9v/60XbnwlocGfiD7rcuenhqSVoJx/6HOmeKdgAZySHowGGxgS6Gr2I=
