language: node_js
node_js:
- node
install:
- npm install
- npm install marpat
before_script:
- node --version
- npm --version
after_success: npm run coverage
env:
  global:
  - NODE_ENV=test
  - secure: mlvyYshIaAROuRZXC1GtVh7QR3b5gnp9JtGMno5NeW+95wnmSjSTzoatmAdwYhJhXFWy7DFGWPa9LV9LBVdc2iN6Q3exipym8ResBrHGDcBwRPopur3nCNnVsvGs0vV5m42g9O67RxJLanG1Op/UT4OzF6H7HA4IjPkDGcPrvM6slYht9FePa9l4mSGy046loGrMPKkJb8pj7omR84AkCPn1YhjG2MfbUsv3T1JiLdnbSKAgklGYLiew+xjWsHJiEqTwcyapuFYcbDgYfeHwDylFQXyN5sVW5GWNujyHjBBjjBtBLHFJo44Vo+exN3sAH33INlZpPBk9b5h2jq8qHtrn/hciQfvtjjthdhhkOZdCS5D13yoVULL7EjBjR3XsmHHtNfCUJi9JNNs9SoGNv1o1EAfKC0Sb+GnWeeYnEoG3BIfQS8U4H6MOUjBDgC6RE9tpibLb+VNQlYCUhAxDJXY35ZnmkejxQs4xgBnTXOXP3sUbe/k25B1CKMKMmVZ7GxhVUS6SMZXdhga2VOaQR1OdzhVFdexrOJgu/d7H+irmYQHmJx+pc+cMwU3IfsJFaLPgGNtBmmi4VUBPkaInGdBre4h0LLAEvICaLacY/9etHl1Wq4rvWPfcFr9jxLENiD0J8HgRjIefOHtITo+OGJWEfwBIotd+AlSqplYo1uE=
  - secure: Qy5gWTw91/AAmWWbZMQE+YjgvsaLlf7jBbQz+6ngBylcA6s1/tE1HByCNx6Qz0h2cEnp6qAOEPHyP6yuss03pDSh5o1MCI+OI/CajrxEDGEX6ROzxg9TW6uy7mkg19flSIxJdvcpJzuTGVjXsKthocseQFu7tELYbifYP5/kSgBulrptLXdjpkWsrga28s8RyrB2J9/u2G2/9THSzzZIIYhppYRYJaxdbrsnr/mwgMsmwi12aOTxSVjkVV8KOEsp0HFcHuUnioafLK9qyM4beYNpyDB/FNxSmssxp+JY18R3jIDyMOOwO/fElKkJ8Cj1R1j5VVjs0BwIkWM6cArAw7oEKLYi9e89h30aPuHmZRSE5W9PKN0E5hggdLGrfHNuiEmHjtUg6lyzr2bxIvQQ6rRxO7+jP4A/seWh/ieWFEBkkN97zRmZ7khkXAL5V2nkCXz3PmIHo9hx0fmMW7tkE8ACIv+124sgX1zC8lfCQq122EcgtlEK17KiS8JlTBtkQZDIFHQpG8ay91WldD8cpYgwxhCLTI9Wh//NUUJiT7CLWPlUzWvUNj9Hf/3/MuSHGpUE38GrscHdwDM1fMor1mWRGpsm0VqmhiUhNjIK47kA/0JYn3aFw5x+PXloSiOYBQl3R3OwH8osoaADPh1MXKRTNDn61801aBpHMfNqBYo=
